### ISSUE TITLE
`babel-plugin-syntax-dynamic-import` vs `babel-plugin-dynamic-import-node`

### ISSUE THREAD

**Issue by catamphetamine** [airbnb/babel-plugin-dynamic-import-node#60]
What's the difference between `babel-plugin-syntax-dynamic-import` vs `babel-plugin-dynamic-import-node`?
I tried `babel-plugin-syntax-dynamic-import` and it works fine for my Webpack v4 setup.
Why would I consider `babel-plugin-dynamic-import-node` instead?

**Comment by ljharb** [comment]
The first merely enables babel to parse the syntax; the second actually transforms it.

Webpack can understand import syntax natively, so you don't need the transform - but you *would* need it for running tests in node.

**Comment by wd2010** [comment]
@ljharb I get a trouble for `syntax-dynamic-import`.  I use the `import()` in my project and I don`t use `syntax-dynamic-import`  because webpack can understand it, but there is a error when `babel-loader` transform it. 
The error is:
```
ERROR in ./index.js
Module build failed (from ../node_modules/happypack/loader.js):
SyntaxError: C:\Users\enawned\Documents\demos\webpack4-demo\src\index.js: Support for the experimental syntax 'dynamicImport' isn't currently enabled (10:34):

   8 |   if(module.hot){
   9 |     module.hot.accept('./components/App.jsx',async ()=>{
> 10 |       let {default: Comp}= await import('./components/App.jsx');
     |                                  ^
  11 |       render(<Comp />, document.getElementById('root'));
  12 |     });
  13 |   }

Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.
    at _class.raise (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:4028:15)
    at _class.expectPlugin (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:5364:18)
    at _class.parseExprAtom (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:6348:14)
    at _class.parseExprAtom (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:3724:52)
    at _class.parseExprSubscripts (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:6081:21)
    at _class.parseMaybeUnary (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:6060:21)
    at _class.parseAwait (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:7279:26)
    at _class.parseExprAtom (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:6376:27)
    at _class.parseExprAtom (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:3724:52)
    at _class.parseExprSubscripts (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:6081:21)
    at _class.parseMaybeUnary (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:6060:21)
    at _class.parseExprOps (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:5945:21)
    at _class.parseMaybeConditional (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:5917:21)
    at _class.parseMaybeAssign (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:5864:21)
    at _class.parseVar (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:8123:26)
    at _class.parseVarStatement (C:\Users\enawned\Documents\demos\webpack4-demo\node_modules\@babel\parser\lib\index.js:7937:10)
 @ multi ../node_modules/webpack-dev-server/client?http://0.0.0.0:8080 ../node_modules/webpack/hot/only-dev-server.js ./index.js main[2]
```
**That means I have to use the plugin of `syntax-dynamic-import` to parse `import()` ?**

the version of `webpack, babel, node, npm` is: 
```js
{
    "webpack": "^4.26.1",
    "@babel/core": "^7.0.0",
    "@babel/plugin-proposal-class-properties": "^7.2.1",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.0",
    "node": "v10.14.1",
    "npm": "6.4.1"
}
```

**Comment by ljharb** [comment]
Yes, you have to manually include the syntax plugin when using webpack (which isn’t related to this repo at all)

**Comment by wd2010** [comment]
Thank you very much ,I  get it .
