### ISSUE TITLE
v2.3.1 introduced a breaking change

### ISSUE THREAD

**Issue by gaje** [airbnb/babel-plugin-dynamic-import-node#87]
```
 Error: No substitution given for "_". If this is not meant to be a
                placeholder you may want to consider passing one of the following options to @babel/template:
                - { placeholderPattern: false, placeholderWhitelist: new Set(['_'])}
                - { placeholderPattern: /^_$/ }

      at metadata.placeholders.forEach.placeholder (node_modules/@babel/template/lib/populate.js:21:15)
          at Array.forEach (<anonymous>)
      at populatePlaceholders (node_modules/@babel/template/lib/populate.js:18:27)
      at arg (node_modules/@babel/template/lib/string.js:22:51)
      at arg (node_modules/@babel/template/lib/builder.js:77:14)
      at node_modules/babel-plugin-dynamic-import-node/lib/utils.js:36:89
      at PluginPass.CallExpression (node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:121:9)
      at newFn (node_modules/@babel/traverse/lib/visitors.js:179:21)
      at NodePath._call (node_modules/@babel/traverse/lib/path/context.js:55:20)
      at NodePath.call (node_modules/@babel/traverse/lib/path/context.js:42:17)
          =============
      at createDynamicImportTransform (node_modules/babel-plugin-dynamic-import-node/lib/utils.js:30:21)
      at _default (node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:22:71)
      at node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
      at node_modules/@babel/core/lib/config/full.js:199:14
      at Function.<anonymous> (node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
      at evaluateSync (node_modules/gensync/index.js:244:28)
```

Rolling back and locking into 2.3.0 resolves the issue.

**Comment by ljharb** [comment]
Thanks - this was already fixed and released as v2.3.2 in #86.
